#!/bin/bash
NUMBER1=$1
NUMBER2=$2

SUM=$(($NUMBER1+$NUMBER2))
echo "$NUMBER1 and $NUMBER2 total is: $SUM"
if [ $SUM -lt 100 ]
 then 
     echo "$SUM is less than 100"
  else
     echo "$SUM is grether than 100"
fi     
