#!/bin/bash
R="\e[31m"
G="\e[32m"
N="\e[0m"
Y="\e[30m"

userid=$(id -u)

if [ $userid -ne 0 ]
   then
       echo -e "$R your not in root user $N"
       exit 1
    else
       echo -e "$G your are in root user....... $N"
fi

for package in $@
  do
    dnf install $package
    if [ $userid -ne 0 ]
      then
          echo -e "$R not installed $package........... $N"
          exit1
        else
           echo -e "$R $package installed completed........ $N"
    fi
done    

      

