#!/bin/bash
R="\e[31m"
G="\e[32m"
N="\e[0m"
numbers=(10 20 30 40 50)
echo -e "first number of arrey is: $R ${numbers[0]} $N"
echo "second number of arrey is: ${numbers[1]}"
echo "third number of arrey is: ${numbers[2]}"
